### ISSUE TITLE
Imporve Css

### ISSUE THREAD

**Issue by Joshuajrodrigues** [Joshuajrodrigues/pets-survey-form-fcc#1]
Go nuts, try to improve the css as best as you can

**Comment by Shubhainder** [comment]
Can help with this. Anything particular you want?

**Comment by Joshuajrodrigues** [comment]
> Can help with this. Anything particular you want?

Sure go ahead and use your imagination, but dont change the html file logic please.

**Comment by Shubhainder** [comment]
Sure! Also, where can I contact you?

**Comment by Joshuajrodrigues** [comment]
Right here

**Comment by Shubhainder** [comment]
Okay

**Comment by Shubhainder** [comment]
After the work can you give me a recommendation, will appreciate it  :)

**Comment by Joshuajrodrigues** [comment]
Yeah

**Comment by Joshuajrodrigues** [comment]
by recommendation you mean feedback right ?

**Comment by Shubhainder** [comment]
Yeah!
